workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_ID: "com.example.app" # Your app bundle ID
      groups:
        - app_store_credentials  # Contains Apple API key, issuer ID, key ID
        - ios_signing            # Contains certificate and provisioning profile
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build iOS Release
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=1

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
